# =============================================
# Configuration Email (Gmail SMTP)
# =============================================
# Remplacez par votre email Gmail
email.sender=eyahmad03@gmail.com
# Remplacez par votre "App Password" Gmail (pas votre mot de passe normal)
# Activez : Google Account > Securite > Authentification 2 facteurs > App Passwords
email.password=ccyzgldyaucxtgrm
email.smtp.host=smtp.gmail.com
email.smtp.port=587
email.app.name=Psychology App

# =============================================
# Configuration ImgBB (Image Upload)
# =============================================
# Obtenez votre clé API gratuite sur https://api.imgbb.com/
imgbb.api_key=0a09accb8ab3c518c68f0a402e12fc5c


# =============================================
# Configuration Face++ (Reconnaissance Faciale)
# =============================================
# Obtenez vos identifiants sur https://www.faceplusplus.com/
faceplusplus.api_key=WcNhtR7CgcEjyaCA0Lghlf4QsJZS2RJ9
faceplusplus.api_secret=F4toizN_gp1FaUQRchwEqtAxDAZqlD_l
# =============================================
# Configuration Gemini AI
# =============================================
gemini.api.key=AIzaSyALcEYTVenV1k54Vgm8EycSp4M5M9HAvtI